- clean: ['~']

- link:
    ~/.bash_profile:
    ~/.bashrc: 
    ~/.dotfiles: ""
    ~/.gitconfig:
    ~/.vimrc:
    ~/.config/nvim/init.vim: 
        path: "vimrc"
        create: true
    ~/.zshrc: 
