- clean: ['~']

- link:
    ~/.bash_profile:
    ~/.bashrc: 
    ~/.dotfiles: ""
    ~/.gitconfig:
    ~/.vimrc:
    ~/.zshrc: 
    /usr/local/share/fonts/NerdFonts:
        if: '[ $EUID -eq 0 ]'
        path: fonts/NerdFonts
