- clean: ['~']

- create:
    - ~/.config

- link:
    ~/.bash_profile:
    ~/.bashrc: 
    ~/.dotfiles: ""
    ~/.gitconfig:
    ~/.vim:
    ~/.vimrc:
    ~/.zshrc: 
    /usr/local/share/fonts/NerdFonts:
        if: '[ $EUID -eq 0 ]'
        path: fonts/NerdFonts

- shell:
    - lib/fzf/install --xdg --key-bindings --completion --no-update-rc 
